### ISSUE TITLE
Federation is failing with HTTP 403

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/repo_meta_to_cmdb#13]
Here's what happened just now.

```
403 Client Error: Forbidden for url: https://it.byu.edu/api/now/v2/table/cmdb_ci_application_software/2ce79fbc4f6ccf40aa42d49f0310c77e: HTTPError
Traceback (most recent call last):
File "/var/task/temporary_handler.py", line 42, in handler
return index.handler(event, context)
File "/var/task/index.py", line 116, in handler
service_now.flush()
File "/var/task/lib/service_now.py", line 108, in flush
loop.run_until_complete(future)
File "/var/lang/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
return future.result()
File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/var/task/lib/service_now.py", line 653, in send
response.raise_for_status()
File "/var/task/requests/models.py", line 935, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://it.byu.edu/api/now/v2/table/cmdb_ci_application_software/2ce79fbc4f6ccf40aa42d49f0310c77e
```

More detail in the CloudWatch -> Log Groups -> /aws/lambda/repo-meta-to-cmdb-prd-function-apigateway -> 2017/08/16/[$LATEST]0c7c40193d114655a9ac84485a955fd0

**Comment by brettbeatty** [comment]
This is a bug with a business rule in ServiceNow that prevents duplicate composite names.
